name: Validate memory cases

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, review_requested, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: monster-memory-cases
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: npm
          cache-dependency-path: ./monster-memory-cases
      - name: Run bitron script
        working-directory: monster-memory-cases
        run: |-
          npm i @lilacgrimoire/bitron
          npx bitron --no-output